### ISSUE TITLE
Samsung A32 not loading 

### ISSUE THREAD

**Issue by PaHorton** [ViciousFish/buzzwords#54]
My friend has a Samsung phone and is unable to load anything anymore. I've attached screenshots of what she sees. She used to be able to load this. 
![Screenshot_20220201-162210_Chrome-1](https://user-images.githubusercontent.com/13230281/152068871-e1eb1d6c-120a-4260-bd25-844aa569abe6.jpg)
![Screenshot_20220201-162228_Chrome](https://user-images.githubusercontent.com/13230281/152068888-831f5129-2237-4311-b61e-ec5ac23a218c.jpg)

**Comment by chuckdries** [comment]
Any browser extensions?

**Comment by PaHorton** [comment]
![Screenshot_20220202-083634_Chrome](https://user-images.githubusercontent.com/13230281/152186101-09e8503f-2f62-4119-9e37-1734907170cb.jpg)
Here's their browser info. No extensions

**Comment by PaHorton** [comment]
Screenshot of the console
![Capture](https://user-images.githubusercontent.com/13230281/152856553-ecf6b8e1-e9ff-40da-9a24-682c7fc7b2d5.png)

And the full log
```
index.e09052e1.js:3 0px
index.e09052e1.js:3 726px
Play.e14858f2.js:4 set current game QXmdH5Y0K2PhCVIl1HmBh
index.e09052e1.js:3 attempted to mark null game as seen QXmdH5Y0K2PhCVIl1HmBh
index.e09052e1.js:3 726px
vendor.9f936e41.js:2971 THREE.WebGLRenderer: Error creating WebGL context.
St @ vendor.9f936e41.js:2971
K7 @ vendor.9f936e41.js:3248
eW @ vendor.9f936e41.js:3248
(anonymous) @ vendor.9f936e41.js:3248
Q5 @ vendor.9f936e41.js:32
nF @ vendor.9f936e41.js:34
n.unstable_runWithPriority @ vendor.9f936e41.js:19
va @ vendor.9f936e41.js:30
Sa @ vendor.9f936e41.js:34
Jx @ vendor.9f936e41.js:32
(anonymous) @ vendor.9f936e41.js:30
n.unstable_runWithPriority @ vendor.9f936e41.js:19
va @ vendor.9f936e41.js:30
x3 @ vendor.9f936e41.js:30
zi @ vendor.9f936e41.js:30
ps @ vendor.9f936e41.js:32
Rx @ vendor.9f936e41.js:30
y @ vendor.9f936e41.js:3248
l @ vendor.9f936e41.js:3248
setTimeout (async)
l @ vendor.9f936e41.js:3248
setTimeout (async)
u @ vendor.9f936e41.js:3248
vendor.9f936e41.js:32 Error: Error creating WebGL context.
    at new St (vendor.9f936e41.js:2971:46274)
    at K7 (vendor.9f936e41.js:3248:27468)
    at eW (vendor.9f936e41.js:3248:28285)
    at vendor.9f936e41.js:3248:25759
    at Q5 (vendor.9f936e41.js:32:1442)
    at nF (vendor.9f936e41.js:34:5093)
    at n.unstable_runWithPriority (vendor.9f936e41.js:19:3896)
    at va (vendor.9f936e41.js:30:38593)
    at Sa (vendor.9f936e41.js:34:1827)
    at Jx (vendor.9f936e41.js:32:11110)
zx @ vendor.9f936e41.js:32
t.callback @ vendor.9f936e41.js:32
b3 @ vendor.9f936e41.js:30
Q5 @ vendor.9f936e41.js:32
nF @ vendor.9f936e41.js:34
n.unstable_runWithPriority @ vendor.9f936e41.js:19
va @ vendor.9f936e41.js:30
Sa @ vendor.9f936e41.js:34
Jx @ vendor.9f936e41.js:32
(anonymous) @ vendor.9f936e41.js:30
n.unstable_runWithPriority @ vendor.9f936e41.js:19
va @ vendor.9f936e41.js:30
x3 @ vendor.9f936e41.js:30
zi @ vendor.9f936e41.js:30
ps @ vendor.9f936e41.js:32
Rx @ vendor.9f936e41.js:30
y @ vendor.9f936e41.js:3248
l @ vendor.9f936e41.js:3248
setTimeout (async)
l @ vendor.9f936e41.js:3248
setTimeout (async)
u @ vendor.9f936e41.js:3248
vendor.9f936e41.js:2971 Uncaught Error: Error creating WebGL context.
    at new St (vendor.9f936e41.js:2971:46274)
    at K7 (vendor.9f936e41.js:3248:27468)
    at eW (vendor.9f936e41.js:3248:28285)
    at vendor.9f936e41.js:3248:25759
    at Q5 (vendor.9f936e41.js:32:1442)
    at nF (vendor.9f936e41.js:34:5093)
    at n.unstable_runWithPriority (vendor.9f936e41.js:19:3896)
    at va (vendor.9f936e41.js:30:38593)
    at Sa (vendor.9f936e41.js:34:1827)
    at Jx (vendor.9f936e41.js:32:11110)
St @ vendor.9f936e41.js:2971
K7 @ vendor.9f936e41.js:3248
eW @ vendor.9f936e41.js:3248
(anonymous) @ vendor.9f936e41.js:3248
Q5 @ vendor.9f936e41.js:32
nF @ vendor.9f936e41.js:34
n.unstable_runWithPriority @ vendor.9f936e41.js:19
va @ vendor.9f936e41.js:30
Sa @ vendor.9f936e41.js:34
Jx @ vendor.9f936e41.js:32
(anonymous) @ vendor.9f936e41.js:30
n.unstable_runWithPriority @ vendor.9f936e41.js:19
va @ vendor.9f936e41.js:30
x3 @ vendor.9f936e41.js:30
zi @ vendor.9f936e41.js:30
ps @ vendor.9f936e41.js:32
Rx @ vendor.9f936e41.js:30
y @ vendor.9f936e41.js:3248
l @ vendor.9f936e41.js:3248
setTimeout (async)
l @ vendor.9f936e41.js:3248
setTimeout (async)
u @ vendor.9f936e41.js:3248
QXmdH5Y0K2PhCVIl1HmBh:1 WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost
vendor.9f936e41.js:2971 THREE.WebGLRenderer: Context Lost.
vendor.9f936e41.js:2923 THREE.WebGLRenderer: WEBGL_lose_context extension not supported.
get @ vendor.9f936e41.js:2923
St.forceContextLoss @ vendor.9f936e41.js:2971
(anonymous) @ vendor.9f936e41.js:3248
setTimeout (async)
(anonymous) @ vendor.9f936e41.js:3248
dM @ vendor.9f936e41.js:3240
VD @ vendor.9f936e41.js:3242
QD @ vendor.9f936e41.js:3244
n.unstable_runWithPriority @ vendor.9f936e41.js:19
oo @ vendor.9f936e41.js:3240
aa @ vendor.9f936e41.js:3244
qy @ vendor.9f936e41.js:3242
(anonymous) @ vendor.9f936e41.js:3240
n.unstable_runWithPriority @ vendor.9f936e41.js:19
oo @ vendor.9f936e41.js:3240
aM @ vendor.9f936e41.js:3240
Ur @ vendor.9f936e41.js:3240
co @ vendor.9f936e41.js:3242
r.updateContainer @ vendor.9f936e41.js:3248
Y4 @ vendor.9f936e41.js:3248
(anonymous) @ vendor.9f936e41.js:3248
uC @ vendor.9f936e41.js:32
hC @ vendor.9f936e41.js:32
nF @ vendor.9f936e41.js:34
n.unstable_runWithPriority @ vendor.9f936e41.js:19
va @ vendor.9f936e41.js:30
Sa @ vendor.9f936e41.js:34
Jx @ vendor.9f936e41.js:32
(anonymous) @ vendor.9f936e41.js:30
n.unstable_runWithPriority @ vendor.9f936e41.js:19
va @ vendor.9f936e41.js:30
x3 @ vendor.9f936e41.js:30
zi @ vendor.9f936e41.js:30
ps @ vendor.9f936e41.js:32
Rx @ vendor.9f936e41.js:30
y @ vendor.9f936e41.js:3248
l @ vendor.9f936e41.js:3248
setTimeout (async)
l @ vendor.9f936e41.js:3248
setTimeout (async)
u @ vendor.9f936e41.js:3248
Show 6 more frames
```

**Comment by chuckdries** [comment]
@PaHorton might not be fixable :/ https://stackoverflow.com/questions/54232528/error-creating-webgl-context-three-js-chrome

can you have your friend try firefox?
